[build]
  # Tell Netlify the Next.js app is in this subfolder
  base = "nextjs-kujisan"
  
  # Run the build command from inside that folder
  command = "npm run build"
  
  # The output folder (relative to the base folder)
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"